### ISSUE TITLE
Momentum will change the pruned weights

### ISSUE THREAD

**Issue by x1155665** [larry0123du/Deep-Compression#2]
Hi, thanks for the code!

According to deep compression, the pruned weights should stay zero in the later runs. However,
due to the functionality of momentum, the values of the newly pruned weights will be changed by the optimizer, since the grads of these weights aren't zero in the last epoch. 

Do you have any idea to solve this problem without setting the momentum to zero?

**Comment by ruihangdu** [comment]
@x1155665 I think in my code I've also masked the gradients so the gradients of the weights that are pruned should've also been zeroed during training.
